### ISSUE TITLE
Memory consumption of images

### ISSUE THREAD

**Issue by LukasKuehne** [gap-packages/images#14]
Hi,

the code below computes the minimal image of all 2^16 subsets of vertices of the 4-cube under the symmetry group of the 4-cube. It takes about 3 minutes. It however also allocates about 16 GB of memory in the process.

```GAP
gap> G4 := Group([(2,3,5,9)(4,7,13,10)(8,15,14,12)(6,11), (1,3)(2,4)(5,7)(6,8)(9,11)(10,12)(13,15)(14,16),
>     (1,2)(3,4)(5,6)(7,8)(9,10)(11,12)(13,14)(15,16),(1,5)(2,6)(3,7)(4,8)(9,13)(10,14)(11,15)(12,16),
>     (1,9)(2,10)(3,11)(4,12)(5,13)(6,14)(7,15)(8,16),(1,4)(5,8)(9,12)(13,16)]);
<permutation group with 6 generators>
gap> compute_all_min_images_4 := function( )
>     local i;
>     for i in IteratorOfCombinations([1 .. 2^4]) do
>         MinimalImage(G4,i,OnSets);
>     od;
> end;
function(  ) ... end
gap> TotalMemoryAllocated();
117177933
gap> compute_all_min_images_4();
gap> TotalMemoryAllocated();
17068628483
gap>
```

I am using GAP 4.10.2, ferret 1.0.2, images 1.3.0.

Best,

Lukas

**Comment by fingolfin** [comment]
Not an author of this package, and two years late, but some observations: first, to calibrate, on my macBook Pro M1 with GAP 4.12.1 the above code takes about 40 seconds (vs. 3 minutes). The memory figures are similar enough (going from `357439909` to `16969551690`)

Next, a "naive" alternative computation only takes 32 seconds and takes 8 GB of memory:
```
gap> G4 := Group([(2,3,5,9)(4,7,13,10)(8,15,14,12)(6,11), (1,3)(2,4)(5,7)(6,8)(9,11)(10,12)(13,15)(14,16),
>     (1,2)(3,4)(5,6)(7,8)(9,10)(11,12)(13,14)(15,16),(1,5)(2,6)(3,7)(4,8)(9,13)(10,14)(11,15)(12,16),
>     (1,9)(2,10)(3,11)(4,12)(5,13)(6,14)(7,15)(8,16),(1,4)(5,8)(9,12)(13,16)]);
<permutation group with 6 generators>
gap> TotalMemoryAllocated();
354396364
gap> mins:=List(IteratorOfCombinations([1 .. 2^4]), x -> First(Set(Orbit(G4,x,OnSets))));; time; TotalMemoryAllocated();
32724
8697006994
```

Of course if the domain stays the same (all subsets of `[1 .. 2^4]`) one can do MUCH better by precomputing the orbits at the start and then doing lookups:
```
gap> G4 := Group([(2,3,5,9)(4,7,13,10)(8,15,14,12)(6,11), (1,3)(2,4)(5,7)(6,8)(9,11)(10,12)(13,15)(14,16),
>     (1,2)(3,4)(5,6)(7,8)(9,10)(11,12)(13,14)(15,16),(1,5)(2,6)(3,7)(4,8)(9,13)(10,14)(11,15)(12,16),
>     (1,9)(2,10)(3,11)(4,12)(5,13)(6,14)(7,15)(8,16),(1,4)(5,8)(9,12)(13,16)]);
<permutation group with 6 generators>
gap> TotalMemoryAllocated();
354398531
gap> dom:=Combinations([1 .. 2^4]);; time; TotalMemoryAllocated();
28
379651005
gap> orbs:=List(OrbitsDomain(G4, dom, OnSets), AsSet);; time; TotalMemoryAllocated();
545
623610468
```
So this was about half a second. And now we can compute minimal images via a simple lookup.

**Comment by ChrisJefferson** [comment]
Just to say I'm going to close this -- while there is lots of memory usage, it's hard to reduce, from how the algorithm works. You can however do much better with vole (although it may take longer for such easy problems).
