### ISSUE TITLE
CanonicalImage for permutations slow

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/images#5]
Doing `CanonicalImage(G, perm)` is way slower than doing `Minimum( Orbit(..) )`.

@athevis is interested in this.

**Comment by ChrisJefferson** [comment]
I realise this is a *very* old issue, but we now have a new package (vole), which should hopefully be much better at this, if @athevis is still interested.

Even if not, it would be nice to know your problem, so we could use it as a benchmark.
