### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/images#7]
The README mentions the license, but would be useful to follow the standard practice - will make things easier.

---

Even more - the README refers to missing files COPYRIGHT.md and LICENSE.

**Comment by ChrisJefferson** [comment]
Removed reference to license and copyright.md in readme

**Comment by olexandr-konovalov** [comment]
Thanks, but it will still be useful to add the `LICENSE` file (many GAP packages have it). It does not require much efforts to add it, and helps when providers of alternative distributions check what is the status of the package.

**Comment by ChrisJefferson** [comment]
OK. I've bloody done it.
